version: "3.8"

services:
  flask_app:
    build:
      context: .
    container_name: "two_tier_backend"
    network:
      - two-tier-app
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Test@123"
      MYSQL_DATABASE: "devops"
    restart: always
    ports:
      - "3306:3306"
    network: 
      - two-tier-app
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost" "-uroot", "-pTest@123"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5

networks:
  two-tier-app:

volumes:
  mysql-data:
